ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer-cloudflare
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: iacassets.launchpad.ot-t-az1.l12m.nl
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: iac-assets-launchpad-tls
    hosts:
      - iacassets.launchpad.ot-t-az1.l12m.nl
